# Generated by Django 5.0.9 on 2024-09-30 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_alter_requestrecord_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
